// <auto-generated />
namespace EF_Task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Version13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version13));
        
        string IMigrationMetadata.Id
        {
            get { return "201803220846381_Version1.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
